// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKA0Kr5m_Y70VhOOpHeSnPsRRB3u9i-Io',
    appId: '1:494646160356:web:f4242b7a6a5084ae9775f1',
    messagingSenderId: '494646160356',
    projectId: 'medicine-app-2026',
    authDomain: 'medicine-app-2026.firebaseapp.com',
    storageBucket: 'medicine-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJy5TBreTywGovxTn1heucQdZdQEnpvcA',
    appId: '1:494646160356:android:649add3572fdaa9d9775f1',
    messagingSenderId: '494646160356',
    projectId: 'medicine-app-2026',
    storageBucket: 'medicine-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChydtQnEogDvKtBCQCfvEtkIHxmSsmNQw',
    appId: '1:494646160356:ios:a5783f9897318d429775f1',
    messagingSenderId: '494646160356',
    projectId: 'medicine-app-2026',
    storageBucket: 'medicine-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
