import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:myapp/models/medicine.dart';
import 'package:myapp/models/medicine_log.dart';
import 'package:myapp/models/health_log.dart';
import 'package:intl/intl.dart';

Future<void> generateAndSharePdf(
  double overallCompliance,
  List<Medicine> medicines,
  List<MedicineLog> logs,
  List<HealthLog> healthLogs,
  String aiClinicalNotes,
  String patientName,
) async {
  final pdf = pw.Document();
  final now = DateTime.now();
  final dateFormat = DateFormat('MMM dd, yyyy');
  final timeFormat = DateFormat('hh:mm a');

  // Define Styles
  final headerStyle = pw.TextStyle(
      fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal);
  final subHeaderStyle = pw.TextStyle(
      fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700);
  final bodyStyle = pw.TextStyle(fontSize: 12);
  final footerStyle = pw.TextStyle(fontSize: 10, color: PdfColors.grey600);

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (context) => pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('HEALTH ADHERENCE REPORT', style: headerStyle),
          pw.Text(dateFormat.format(now), style: bodyStyle),
        ],
      ),
      footer: (context) => pw.Column(
        children: [
          pw.Divider(color: PdfColors.teal),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by AI Medication Manager', style: footerStyle),
              pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                  style: footerStyle),
            ],
          ),
        ],
      ),
      build: (pw.Context context) {
        return [
          pw.SizedBox(height: 20),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('PATIENT INFORMATION',
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold, fontSize: 14)),
                    pw.SizedBox(height: 4),
                    pw.Text('Name: $patientName', style: bodyStyle),
                    pw.Text('Report Period: Last 30 Days', style: bodyStyle),
                  ],
                ),
              ),
              pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                decoration: pw.BoxDecoration(
                  color: overallCompliance >= 80
                      ? PdfColors.green50
                      : (overallCompliance >= 50
                          ? PdfColors.orange50
                          : PdfColors.red50),
                  borderRadius: pw.BorderRadius.circular(8),
                  border: pw.Border.all(
                      color: overallCompliance >= 80
                          ? PdfColors.green
                          : (overallCompliance >= 50
                              ? PdfColors.orange
                              : PdfColors.red)),
                ),
                child: pw.Column(
                  children: [
                    pw.Text('Overall Adherence',
                        style: pw.TextStyle(
                            fontSize: 10, color: PdfColors.grey700)),
                    pw.Text('${overallCompliance.toInt()}%',
                        style: pw.TextStyle(
                            fontSize: 24,
                            fontWeight: pw.FontWeight.bold,
                            color: overallCompliance >= 80
                                ? PdfColors.green
                                : (overallCompliance >= 50
                                    ? PdfColors.orange
                                    : PdfColors.red))),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 32),
          pw.Text('MEDICATION SUMMARY', style: subHeaderStyle),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
            headers: ['Medication', 'Dosage', 'Frequency', 'Current Stock'],
            data: medicines
                .map((med) => [
                      med.name,
                      med.dosage,
                      med.frequency,
                      '${med.currentStock} left',
                    ])
                .toList(),
          ),
          if (healthLogs.isNotEmpty) ...[
            pw.SizedBox(height: 32),
            pw.Text('HEALTH VITAL READINGS', style: subHeaderStyle),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColors.blueGrey700),
              headers: ['Date', 'Type', 'Reading'],
              data: healthLogs.take(15).map((log) {
                String val = log.value1.toString();
                if (log.type == HealthLogType.bloodPressure) {
                  val =
                      '${log.value1.toInt()}/${log.value2?.toInt() ?? 0} mmHg';
                } else if (log.type == HealthLogType.bloodGlucose) {
                  val = '$val mmol/L';
                } else if (log.type == HealthLogType.inr) {
                  val = 'INR: $val';
                }
                return [
                  dateFormat.format(log.timestamp),
                  log.type.name.toUpperCase(),
                  val,
                ];
              }).toList(),
            ),
          ],
          pw.SizedBox(height: 32),
          pw.Text('RECENT DOSAGE LOGS', style: subHeaderStyle),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headers: ['Date', 'Time', 'Medication', 'Status'],
            data: logs
                .take(20)
                .map((log) => [
                      dateFormat.format(log.timestamp),
                      timeFormat.format(log.timestamp),
                      log.medicineName,
                      'Taken',
                    ])
                .toList(),
          ),
          pw.SizedBox(height: 40),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColors.grey300),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  children: [
                    pw.Text('AI CLINICAL SUMMARY (BY GEMINI)',
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.teal900)),
                    pw.SizedBox(width: 8),
                    pw.Text('• Clinician Review Recommended',
                        style: footerStyle),
                  ],
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  aiClinicalNotes,
                  style: bodyStyle.copyWith(fontStyle: pw.FontStyle.italic),
                ),
              ],
            ),
          ),
        ];
      },
    ),
  );

  await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'Medication_Report_${patientName.replaceAll(' ', '_')}.pdf');
}
